name: firebase
version: 0.1.1+3
authors:
- Anant Narayanan <anant@kix.in>
- Seth Ladd <sethladd@gmail.com>
description: A Dart wrapper for Firebase.
homepage: https://github.com/firebase/firebase-dart/
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  unittest: '>=0.11.0 <0.12.0'
