name: firebase_interop
description: Firebase libraries for Dart on the web.
version: 0.1.0
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_interop

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  js: ^0.6.0

dev_dependencies:
  path: ^1.3.9
  pedantic: ^1.3.0
  test: ^1.6.0
  service_worker: ^0.2.0

  build_runner: ^1.0.0
  build_test: ^1.0.0
  build_web_compilers: ">=1.2.0 <3.0.0"
